'use client';
import { useState } from 'react';

export default function ContributePage(){
  const [step,setStep]=useState(1); const [done,setDone]=useState(false); const [sharing,setSharing]=useState('review');
  if(done)return <main className="contribute-page"><section className="contribute-shell thank-you"><strong>소중한 기억을 보내주셔서 감사합니다.</strong><p>바로 공개되지 않으며 가족이 확인한 후 선택하신 방식으로 보관하거나 게시합니다.</p><a href="/community">추억 이야기로 돌아가기</a></section></main>;
  return <main className="contribute-page"><a className="contribute-back" href="/community">← 추억 이야기로 돌아가기</a><section className="contribute-shell">
    <p className="section-kicker">1분이면 충분합니다</p><h1>사진과 추억 보내기</h1><div className="step-indicator" aria-label={`3단계 중 ${step}단계`}><span className={step>=1?'active':''}>1 사진</span><span className={step>=2?'active':''}>2 추억</span><span className={step>=3?'active':''}>3 확인</span></div>
    {step===1&&<div className="contribute-step"><h2>사진을 선택해 주세요</h2><p>사진이나 짧은 영상을 여러 장 선택할 수 있습니다.</p><label className="large-file-button">＋ 사진 선택하기<input type="file" accept="image/*,video/*" multiple /></label><button onClick={()=>setStep(2)}>다음</button></div>}
    {step===2&&<div className="contribute-step"><h2>아시는 이야기를 적어주세요</h2><label>성함<input placeholder="성함을 입력해 주세요" /></label><label>교수님과의 인연<select defaultValue=""><option value="" disabled>선택해 주세요</option><option>가족·친지</option><option>친구</option><option>제자</option><option>교수·학계 동료</option><option>기타</option></select></label><label>추억 이야기 <span>선택사항</span><textarea rows={5} placeholder="언제, 어디에서 찍은 사진인지 또는 기억나는 이야기를 적어주세요" /></label><div className="step-buttons"><button className="quiet" onClick={()=>setStep(1)}>이전</button><button onClick={()=>setStep(3)}>다음</button></div></div>}
    {step===3&&<div className="contribute-step consent-step"><h2>어떻게 전달할까요?</h2><label className="sharing-choice"><input type="radio" name="sharing" checked={sharing==='review'} onChange={()=>setSharing('review')}/><span><strong>사이트 공개를 요청합니다</strong>가족이 사진 속 인물과 내용을 확인한 뒤 공개합니다.</span></label><label className="sharing-choice"><input type="radio" name="sharing" checked={sharing==='family'} onChange={()=>setSharing('family')}/><span><strong>가족에게만 전달합니다</strong>공개하지 않고 가족 자료로만 보관합니다.</span></label><label className="consent"><input required type="checkbox"/> 이 사진을 제공할 권한이 있으며, 제 얼굴이 있다면 선택한 방식으로 사용하는 것에 동의합니다.</label><label className="consent"><input required type="checkbox"/> 함께 나온 분들의 공개 여부를 확인했거나, 확인하지 못한 분이 있음을 가족에게 알리겠습니다.</label><div className="privacy-note"><strong>사진은 바로 공개되지 않습니다.</strong><span>가족 관리자가 공개 가능 여부를 먼저 확인합니다.</span></div><div className="step-buttons"><button className="quiet" onClick={()=>setStep(2)}>이전</button><button onClick={()=>setDone(true)}>가족에게 보내기</button></div></div>}
  </section></main>;
}
