const milestones = [
  { year: '1977', label: 'B.S., Seoul National University College of Pharmacy' },
  { year: '1989', label: 'Ph.D. in Chemistry, UCLA' },
  { year: '1993', label: 'Joined Sungkyunkwan University' },
  { year: '2019', label: 'President, Korean Society of Organic Synthesis' },
];

export default function EnglishHome(){
  return <main>
    <section className="hero" id="home"><header className="site-header"><a className="wordmark" href="/en"><span className="wordmark-ko">Professor Young Hoon Jung</span><span className="wordmark-en">In loving memory</span></a><nav className="desktop-nav" aria-label="Main navigation"><a href="#life">His Life</a><a href="#teaching">Teaching &amp; Research</a><a href="#photos">Life in Photos</a><a href="#directions">Funeral Hall</a><a href="#memories">Share a Memory</a></nav><a className="language-button" href="/" aria-label="한국어로 보기">한국어</a></header><div className="hero-portrait" role="img" aria-label="Portrait placeholder"><span>PORTRAIT</span></div><div className="hero-shade"/><div className="hero-content"><p className="eyebrow">In loving memory</p><h1>Professor<br/>Young Hoon Jung</h1><p className="dates">Life dates to be confirmed</p><blockquote>A beloved father, teacher, scholar, and mentor whose warmth and dedication continue to inspire us.</blockquote><div className="hero-actions"><a className="primary-action" href="#life">His Life</a><a className="secondary-action" href="#memories">Share a Memory</a></div></div></section>
    <section className="intro section-shell" id="life"><p className="section-kicker">A life of scholarship and devotion</p><div className="intro-grid"><h2>A passion for discovery.<br/>A gift for teaching.</h2><div><p>Professor Young Hoon Jung devoted his life to organic medicinal chemistry and to mentoring generations of students. His scholarship, warmth, and generosity left an enduring mark on his family, friends, colleagues, and students.</p><a className="text-link" href="#teaching">Read his story <span>→</span></a></div></div><div className="milestones">{milestones.map(item=><article key={item.year}><strong>{item.year}</strong><span>{item.label}</span></article>)}</div></section>
    <section className="photo-section" id="photos"><div className="section-shell"><div className="section-heading"><div><p className="section-kicker">Life in photos</p><h2>Moments We Remember</h2></div></div><div className="album-grid"><article className="album-card warm"><div className="album-placeholder"><span>PHOTO 1</span></div><p>Family</p><h3>With Family</h3></article><article className="album-card blue"><div className="album-placeholder"><span>PHOTO 2</span></div><p>Friends</p><h3>Among Friends</h3></article><article className="album-card green"><div className="album-placeholder"><span>PHOTO 3</span></div><p>Teaching &amp; Research</p><h3>A Life in Scholarship</h3></article></div></div></section>
    <section className="legacy section-shell" id="teaching"><div className="legacy-mark" aria-hidden="true">學</div><div><p className="section-kicker">Teaching &amp; research</p><h2>A Legacy of Learning</h2><p>His work advanced organic and medicinal chemistry, while his greatest legacy lives on through the students and colleagues he guided.</p></div></section>
    <section className="directions section-shell" id="directions"><div><p className="section-kicker">Funeral hall &amp; directions</p><h2>Visitation Information</h2><p>The information shown is a placeholder and will be updated by the family.</p></div><article className="directions-card"><p className="example-label">SAMPLE INFORMATION</p><h3>Seonggyun Memorial Hall, Chrysanthemum Room</h3><address>123 Example-ro, Jongno-gu, Seoul</address><dl><div><dt>Visitation</dt><dd>From 10:00 a.m., August 25, 2026</dd></div><div><dt>Transit</dt><dd>Five-minute walk from Exit 2, Example Station</dd></div><div><dt>Parking</dt><dd>Underground parking is available</dd></div></dl><a href="#directions">Get Directions</a></article></section>
    <section className="memory-invitation" id="memories"><p className="section-kicker">Share a memory</p><h2>Help Us Remember Him</h2><p>Share a photograph, a story, or a lesson you carry with you. Submissions are reviewed by the family before publication.</p><a className="memory-button" href="/contribute">Share a Memory</a></section><footer><span>In Loving Memory of Professor Young Hoon Jung</span><span>한국어 · English</span></footer><MobileNav language="en" />
  </main>;
}
import MobileNav from '../components/MobileNav';
