const milestones = [
  { year: '1957', label: 'Born in Huam-dong, Yongsan-gu, Seoul' },
  { year: '1981', label: 'B.S., Seoul National University College of Pharmacy' },
  { year: '1983', label: 'M.S., Seoul National University College of Pharmacy' },
  { year: '1989', label: 'Ph.D. in Chemistry, UCLA' },
  { year: '1990', label: 'Postdoctoral researcher at Harvard; joined Dongduk Women’s University' },
  { year: '1993', label: 'Joined Sungkyunkwan University College of Pharmacy' },
  { year: '2013–19', label: 'Leadership and service in Korea’s pharmaceutical and organic synthesis societies' },
  { year: '2016–18', label: 'Director, Bio Center at Gyeonggido Business & Science Accelerator' },
  { year: '2023', label: 'Professor Emeritus at SKKU; faculty appointment at Duksung Women’s University' },
  { year: '2024', label: 'Quality-management pharmacist adviser at Samoh Pharmaceutical' },
  { year: '2026', label: 'Passed away on August 24, remembered by family, friends, colleagues, and students' },
];

export default function EnglishHome(){
  return <main>
    <section className="hero" id="home"><header className="site-header"><a className="wordmark" href="/en"><span className="wordmark-ko">Professor Young Hoon Jung</span><span className="wordmark-en">In loving memory</span></a><nav className="desktop-nav" aria-label="Main navigation"><a href="#life">His Life</a><a href="#teaching">Teaching &amp; Research</a><a href="#photos">Life in Photos</a><a href="#directions">Resting Place</a><a href="#memories">Share a Memory</a></nav><Link className="language-button" href="/" aria-label="한국어로 보기">한국어</Link></header><HeroCarousel language="en"/><div className="hero-shade"/><div className="hero-content"><p className="eyebrow">In loving memory</p><h1>Professor<br/>Young Hoon Jung</h1><p className="dates">October 17, 1957 — August 24, 2026</p><blockquote>A beloved father, teacher, scholar, and mentor whose warmth and dedication continue to inspire us.</blockquote><div className="hero-actions"><a className="primary-action" href="#life">His Life</a><a className="secondary-action" href="#memories">Share a Memory</a></div></div></section>
    <section className="intro section-shell" id="life"><p className="section-kicker">A life of scholarship and devotion</p><div className="intro-grid"><h2>A passion for scholarship.<br/>A warmth for people.</h2><div><p>Born on October 17, 1957, in Huam-dong, Seoul, Professor Young Hoon Jung began his academic journey at Seoul National University College of Pharmacy and earned his Ph.D. in Chemistry at UCLA. After continuing his research at Harvard, he devoted decades to research and education at Dongduk Women’s University and Sungkyunkwan University. Even after retirement, he continued serving students, academia, and industry as a professor emeritus, faculty member, and adviser.</p><p className="school-history"><strong>School communities</strong><span>Sunlim Middle School, Class 22 · Kyunggi High School, Class 72 · Seoul National University College of Pharmacy, Class 35</span></p><a className="text-link" href="#teaching">Teaching and research <span>→</span></a></div></div><div className="milestones">{milestones.map(item=><article key={item.year}><strong>{item.year}</strong><span>{item.label}</span></article>)}</div></section>
    <section className="photo-section" id="photos"><div className="section-shell"><div className="section-heading"><div><p className="section-kicker">Life in photos</p><h2>Moments We Remember</h2></div></div><div className="album-grid"><article className="album-card warm"><div className="album-placeholder"><span>PHOTO 1</span></div><p>Family</p><h3>With Family</h3></article><article className="album-card blue"><div className="album-placeholder"><span>PHOTO 2</span></div><p>Friends</p><h3>Among Friends</h3></article><article className="album-card green"><div className="album-placeholder"><span>PHOTO 3</span></div><p>Teaching &amp; Research</p><h3>A Life in Scholarship</h3></article></div></div></section>
    <section className="legacy section-shell" id="teaching"><div className="legacy-mark" aria-hidden="true">學</div><div><p className="section-kicker">Teaching &amp; research</p><h2>A Legacy of Learning</h2><p>His work advanced organic and medicinal chemistry, while his greatest legacy lives on through the students and colleagues he guided.</p></div></section>
    <section className="directions section-shell" id="directions"><div><p className="section-kicker">Visiting his resting place</p><h2>Visiting His Resting Place</h2><p>Directions and visiting information will appear here after the family confirms what may be shared publicly.</p></div><article className="directions-card"><p className="example-label">NOT YET PUBLIC</p><h3>Resting Place &amp; Memorial Visit</h3><address>The family will add the location here.</address><dl><div><dt>Visiting</dt><dd>Hours and meeting point</dd></div><div><dt>Transit</dt><dd>Nearest station and directions</dd></div><div><dt>Parking</dt><dd>Parking location and guidance</dd></div></dl><a href="#directions">View Information</a></article></section>
    <section className="memory-invitation" id="memories"><p className="section-kicker">Share a memory</p><h2>Help Us Remember Him</h2><p>Share a photograph, a story, or a lesson you carry with you. Submissions are reviewed by the family before publication.</p><a className="memory-button" href="/contribute">Share a Memory</a></section><footer><span>In Loving Memory of Professor Young Hoon Jung</span><span>한국어 · English</span></footer><MobileNav language="en" />
  </main>;
}
import MobileNav from '../components/MobileNav';
import HeroCarousel from '../components/HeroCarousel';
import Link from 'next/link';
